# Generated by Django 5.2.7 on 2025-10-30 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 6, 53, 20, 503037, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.time(6, 53, 54, 833808)),
            preserve_default=False,
        ),
    ]
