# Generated by Django 5.2.8 on 2025-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_due_date_task_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
